from constants.game_constants import SCREEN_WIDTH, SCREEN_HEIGHT

GUI_FRAME_DECORATION = "╔═╗║ ║╚═╝"
GUI_FRAME_CROSS_CHARS = "╠╣╦╩╬"

STAT_SECTION_HEIGHT = 7
STAT_SECTION_Y = SCREEN_HEIGHT - STAT_SECTION_HEIGHT

RESOURCE_SECTION_WIDTH = 17

HEALTH_BAR_X = 1
HEALTH_BAR_Y_OFFSET = -6
HEALTH_BAR_WIDTH = RESOURCE_SECTION_WIDTH - 2

EXAMINE_SECTION_WIDTH = 17
EXAMINE_SECTION_X = SCREEN_WIDTH - EXAMINE_SECTION_WIDTH

MESSAGE_SECTION_X = RESOURCE_SECTION_WIDTH - 1
MESSAGE_SECTION_Y = STAT_SECTION_Y
MESSAGE_SECTION_WIDTH = SCREEN_WIDTH - RESOURCE_SECTION_WIDTH - EXAMINE_SECTION_WIDTH + 2

MESSAGE_LOG_X = MESSAGE_SECTION_X + 1
MESSAGE_LOG_Y = MESSAGE_SECTION_Y + 1
MESSAGE_LOG_WIDTH = MESSAGE_SECTION_WIDTH - 2
MESSAGE_LOG_HEIGHT = STAT_SECTION_HEIGHT - 2

ITEM_SELECT_FRAME_WIDTH = 50
ITEM_SELECT_FRAME_HEIGHT = 20
